More refinements

diff --git a/bin/pipeline b/bin/pipeline
--- a/bin/pipeline
+++ b/bin/pipeline
@@ -7,23 +7,29 @@ if [ -z "${dirName}" ] || [ ! -d "${dirName}" ]; then
 fi
 
 phpFiles=$(find "${dirName}" -type f -name '*.php' -and ! -wholename '*/vendor/*' 2>/dev/null);
+echo "Testing $(echo "${phpFiles}" | wc -l) php files";
+echo '';
 
-echo 'Checking for PHP syntax errors...';
+echo '- Checking for PHP syntax errors';
 output=$(echo "${phpFiles}" | xargs -I{} php -l {} | grep 'Errors parsing ' | cut -c16-);
 if [ -n "${output}" ]; then
   echo "${output}" | xargs -I{} echo ' - {}' >&2;
   exit 6;
 fi
 
-echo 'Checking for strict typed classes...';
+echo '- Checking for strict typed classes';
 output=$(echo "${phpFiles}" | xargs -I{} -n1 grep -L 'declare(strict_types=1);' {} | xargs -I{} echo ' - {}');
 if [ -n "${output}" ]; then
   echo "${output}" >&2;
   exit 7;
 fi
 
-echo 'Checking console...';
+echo '- Checking console';
 if ! "${dirName}/bin/console" '\Fugue\Command\TestCommand'; then
-  echo 'Console test failed!' >&2;
-  exit 8;
+  exitCode=$?;
+  echo 'Console failed!' >&2;
+  exit $exitCode;
 fi
+
+echo '';
+echo 'Passed all checks';
