More fixes, and added php-cs-fixer

diff --git a/bin/pipeline b/bin/pipeline
--- a/bin/pipeline
+++ b/bin/pipeline
@@ -24,6 +24,13 @@ if [ -n "${output}" ]; then
   exit 7;
 fi
 
+echo '- Checking code style';
+if ! ./vendor/bin/php-cs-fixer fix -vvv --dry-run --no-interaction --using-cache=no src; then
+  exitCode=$?;
+  echo 'PHP-CS-Fixer failed!' >&2;
+  exit $exitCode;
+fi
+
 echo '- Checking console';
 if ! "${dirName}/bin/console" '\Fugue\Command\TestCommand'; then
   exitCode=$?;
